version: '3.8'

volumes:
  geoserver_data:
    name: geoserver_data

services:

  nginx:
    image: nginx
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/:/etc/ssl/
    restart: unless-stopped

  air:
    image: cosmtrek/air
    working_dir: /air-server/
    volumes:
      - ./air-server/:/air-server/

  geoserver:
    image: docker.osgeo.org/geoserver:2.25.x
    volumes:
      - ./geoserver_data/:/geoserver_data/
    restart: unless-stopped
        
  webcolorblue:
    image: fabricioveronez/web-color:blue
  webcolorgreen:
    image: fabricioveronez/web-color:green
