services:

  nginx:
    image: nginx
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    secrets:
      - source: nginx_cert
        target: /etc/ssl/cert.pem
      - source: nginx_key
        target: /etc/ssl/cert.key
    restart: unless-stopped

  air:
    image: cosmtrek/air
    working_dir: /air-server/
    volumes:
      - ./air-server/:/air-server/

  geoserver:
    image: docker.osgeo.org/geoserver:2.25.x
    environment:
      - CORS_ENABLED=true
      - CORS_ALLOWED_METHODS=GET,POST,PUT,HEAD,OPTIONS
      - SKIP_DEMO_DATA=true
    volumes:
      - type: bind
        source: ./geoserver_data/ 
        target: /opt/geoserver_data/
      - type: bind
        source: ./tomcat_config.xml 
        target: /opt/config_overrides/web.xml
    restart: unless-stopped
        
  webcolorblue:
    image: fabricioveronez/web-color:blue
  webcolorgreen:
    image: fabricioveronez/web-color:green

secrets:
  nginx_cert:
    file: ./certs/cert.pem
  nginx_key:
    file: ./certs/cert.key
