events {
	worker_connections 1024;
}

http {
	server {
		listen			443 ssl;
		ssl_certificate		/etc/ssl/cert.pem;
		ssl_certificate_key 	/etc/ssl/cert.key;
		server_name dev.digo-eu.com www.dev.digo-eu.com;
	}
	server {
		listen			443 ssl;
		ssl_certificate		/etc/ssl/cert.pem;
		ssl_certificate_key 	/etc/ssl/cert.key;
		server_name db.digo-eu.com www.db.digo-eu.com;

    location ~ ^/v1/ping {
      proxy_pass         http://spacetimedb:3000;
      proxy_http_version 1.1;
      proxy_set_header   Upgrade    $http_upgrade;
      proxy_set_header   Connection "Upgrade";
      proxy_set_header   Host       $host;
      proxy_set_header   X-Real-IP  $remote_addr;
    }

    location ~ ^/v1/database/ {
      proxy_pass         http://spacetimedb:3000;
      proxy_http_version 1.1;
      proxy_set_header   Upgrade    $http_upgrade;
      proxy_set_header   Connection "Upgrade";
      proxy_set_header   Host       $host;
      proxy_set_header   X-Real-IP  $remote_addr;
    }

    location ~ ^/v1/[^/]+/call/[^/]+$ {
      proxy_pass         http://spacetimedb:3000;
      proxy_http_version 1.1;
      proxy_set_header  Upgrade $http_upgrade;
      proxy_set_header  Connection "Upgrade";
      proxy_set_header  Host $host;
      proxy_set_header  X-Real-IP  $remote_addr;
    }

    location /v1/identity {
      proxy_pass http://localhost:3000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
      proxy_set_header  X-Real-IP  $remote_addr;
    }

    location / {
      allow 127.0.0.1;
      allow 172.16.0.0/12;
      deny all;
    }
	}
	server {
		listen			443 ssl;
		ssl_certificate		/etc/ssl/cert.pem;
		ssl_certificate_key 	/etc/ssl/cert.key;

		server_name digo-eu.com www.digo-eu.com;

		location /geoserver/ { proxy_pass http://geoserver:8080/geoserver/; }

		location /frappe-bird {
			root				/usr/share/nginx/html/;
			index				index.html;
			default_type application/javascript;

			# Headers para permitir multithreading (SharedArrayBuffer)
			add_header 'Cross-Origin-Embedder-Policy' 'require-corp';
			add_header 'Cross-Origin-Opener-Policy' 'same-origin';

			# Headers para DESATIVAR o Cache
			add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
			if_modified_since off;
			expires off;
			etag off;
		}

		location /fibula {
			root				/usr/share/nginx/html/;
			index			  index.html;
			default_type application/javascript;

			# Headers para permitir multithreading (SharedArrayBuffer)
			add_header 'Cross-Origin-Embedder-Policy' 'require-corp';
			add_header 'Cross-Origin-Opener-Policy' 'same-origin';

			# Headers para DESATIVAR o Cache
			add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
			if_modified_since off;
			expires off;
			etag off;
		}

		location / { 
			proxy_pass http://homepage:3000; 
			# Headers para permitir multithreading (SharedArrayBuffer)
			add_header 'Cross-Origin-Embedder-Policy' 'require-corp';
			add_header 'Cross-Origin-Opener-Policy' 'same-origin';
		}
	}
}
